package personal.authWichProducts.exceptions;

public class RecursoNaoEncontradoException extends  RuntimeException{
    public RecursoNaoEncontradoException(String mensage){
        super(mensage);
    }
}
